# configuration for "master" branch
-
  branches:
    only:
      - master

  version: 1.0.{build}

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  cache:
    - node_modules                        # local npm modules

  after_build:
    - gulp build
    - nuget pack SiteServer.UI.nuspec

  artifacts:
    - path: '*.nupkg'

  deploy:
    - provider: NuGet
      server:                  # remove to push to NuGet.org
      api_key:
        secure: cKpWZvlfFA7EfagAXc/mZfTGHXxfoKNOYTQd6v4ImalbNV1mtNR55M2HMJJ4jCAo
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/

  notifications:
    - provider: GitHubPullRequest
      on_build_success: true
      on_build_failure: true

# configuration for "dev" branch
-
  branches:
    only:
      - dev

  version: 1.0.{build}-beta

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  cache:
    - node_modules                        # local npm modules

  after_build:
    - gulp build
    - nuget pack build/SiteServer.UI.nuspec

  artifacts:
    - path: '*.nupkg'

  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/siteserver/api/v2/package                 # remove to push to NuGet.org
      api_key:
        secure: i9vISdFyCeWbRUQw+jhcF748i4oWdeatGBrx+dJ07SDTpt7Hsk9YCRp/ha3ZXfZF
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/

  notifications:
    - provider: GitHubPullRequest
      on_build_success: true
      on_build_failure: true