environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp
  - npm install

test:
  - gulp build

build: off

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

deploy_script:
  - ps: |
      "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
      iex "npm pack"
      iex "npm publish"
    on:
      branch: master