environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install gulp -g
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

after_build:
  - gulp build

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

test: off

deploy_script:
  - ps: |
      "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
      iex "npm pack"
      iex "npm publish"
    on:
      branch: master